runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|svg|txt))$
  static_files: dist/Koffeecup/\1
  upload: dist/Koffeecup/(.*)
- url: /(.*)
  static_files: dist/Koffeecup/index.html
  upload: dist/Koffeecup/index.html